version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/

      - echo Updating AWS CLI to v2 if already present...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip && ./aws/install --update

      - echo Setting up kubeconfig...
      - export AWS_REGION=us-east-1
      - export CLUSTER_NAME=three-tier-cluster
      - export KUBECONFIG=/root/.kube/config
      - mkdir -p $(dirname $KUBECONFIG)
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

  build:
    commands:
      - echo Verifying access to cluster...
      - kubectl get nodes

      - echo Applying Kubernetes manifests...
      - kubectl apply -f Kubernetes-Manifests-file/Database/
      - kubectl apply -f Kubernetes-Manifests-file/Backend/
      - kubectl apply -f Kubernetes-Manifests-file/Frontend/
      - kubectl apply -f Kubernetes-Manifests-file/ingress.yaml
