version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.30.1/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

      - echo Setting kubeconfig path...
      - export KUBECONFIG=/root/.kube/config
      - mkdir -p $(dirname $KUBECONFIG)

      - echo Updating kubeconfig for EKS cluster...
      - aws eks update-kubeconfig --region us-east-1 --name three-tier-cluster

  build:
    commands:
      - echo Testing cluster access...
      - kubectl get nodes || echo "Failed to connect to cluster"

      - echo Applying Kubernetes manifests...
      - kubectl apply -f Kubernetes-Manifests-file/Database/
      - kubectl apply -f Kubernetes-Manifests-file/Backend/
      - kubectl apply -f Kubernetes-Manifests-file/Frontend/
      - kubectl apply -f Kubernetes-Manifests-file/ingress.yaml
